### ISSUE TITLE
Unknown error for isElementDisplayed

### ISSUE THREAD

**Issue by parasuramankumarasami** [2gis/Winium.Desktop#32] opened 2015-07-29 10:45 UTC
Hi,

I am getting Unknown error for isElementDisplayed. this error is inconsistent.

Please find the below log.
[16:12:29] [Debug] Waiting for a connection...
[16:12:31] [Debug] ACCEPTED REQUEST POST /session/AwesomeSession/elements HTTP/1
.1
[16:12:31] [Info] COMMAND findElements
{
  "sessionId": "AwesomeSession",
  "using": "class name",
  "value": "NetUIListViewItem",
  "SESSIONID": "AwesomeSession"
}
[16:12:31] [Debug] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":[{"ELEMENT":"824816744-14"}
]}
[16:12:31] [Debug] Client closed

[16:12:31] [Debug] Waiting for a connection...
[16:12:31] [Debug] ACCEPTED REQUEST GET /session/AwesomeSession/element/82481674
4-14/displayed HTTP/1.1
[16:12:31] [Info] COMMAND isElementDisplayed
{
  "SESSIONID": "AwesomeSession",
  "ID": "824816744-14"
}
[16:12:31] [Debug] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":13,"value":"Unknown error: "}
[16:12:31] [Debug] Client closed

[16:12:31] [Debug] Waiting for a connection..

**Comment by skyline-gleb** [comment] 2015-07-29 11:25
We will check.

**Comment by skyline-gleb** [comment] 2015-07-31 06:31
Hi,
I cannot reproduce, but resolving this #35 issue will help see more error information

**Comment by skyline-gleb** [comment] 2015-09-21 05:51
Hi,
have new information?

**Closed** 2016-09-21 10:42 UTC
