### ISSUE TITLE
Issue when using Windows 10

### ISSUE THREAD

**Issue by WMaxZimmerman** [2gis/Winium.Desktop#120] opened 2016-09-06 13:41 UTC
Hello, I am currently trying to create a project that uses Winium on Windows 10.  (I have created a similar project on Windows 7 that runs with no issues.)  The problem is that on Windows 10 there is a different calculator, so I downloaded a remake of the old version.  When I run my code the first button click works, but all of the button clicks after that are all over the place (not even in the calculator application).  I have tested with a fresh pull of Winium and with Cruciatus directly.  All of them produced the same issue.  Is there something broken with the application I am using, or is this an issue with Winium/Cruciatus?

If this isn't an issue with Winium/Cruciatus does anyone have a good program that they use for testing in Windows 10? The program I was trying to use is 'http://winaero.com/download.php?view.1795'

**Comment by NickAb** [comment] 2016-09-14 14:07
This might be caused by screen scale not being at 100%. If you have retina screen, then you might have non 100% scale. At least we experienced similar problems on Windows 8.1 when we changed default text size to bigger size (150% dpi) in Appearance and Personalization. This problem might also be caused when running Windows as virtual machine on a host machine with retina screen, for example, when running Windows in VM on Macbook Pro Retina.

**Comment by WMaxZimmerman** [comment] 2016-09-20 14:33
Thanks for the update.  I was running this on my surface book, so I am pretty sure that it would be scaled oddly.  I will double check tonight and let you know if this is my issue.

**Comment by WMaxZimmerman** [comment] 2016-09-21 00:06
I looked at the scaling and found the text scaling was set at 200%.  I set this to 100% but the issue is still occurring.  the tool is able to click the first button, but after that is acts as though it can't find the items and click randomly (not actually random as it clicks the same spots each time).  Any idea what may be causing this?

**Comment by WMaxZimmerman** [comment] 2016-09-21 01:35
After restarting the machine and trying again, I found that it worked!

**Comment by skyline-gleb** [comment] 2016-09-21 04:37
@WMaxZimmerman it's great news!
I created enhancement issue #123 for support non 100% text scale. Can close this issue?

**Comment by WMaxZimmerman** [comment] 2016-09-23 17:11
Yes, I would consider my issue closed.  Thanks.

**Closed** 2016-09-30 05:22 UTC
